version: '3'

services:
  frontend:
    command: npm run start
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  api:
    command: npm run start:dev
    volumes:
      - ./api/src:/usr/src/app/src

  auth: 
    command: npm run start:dev
    volumes:
      - ./auth/src:/usr/src/app/src

  nginx:    
    volumes: 
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
