apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: root                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
     labels:
       app: root               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      containers:
        - image: cfif2001/root:0.3       # образ Docker
          name: root           # ім'я контейнеру
          ports:
            - containerPort: 8080 
          env:
            - name: API_URL
              value: "http://api-service:80"
