apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: demo
          - name: POSTGRES_USER
            value: demo
          - name: POSTGRES_PASSWORD # так працювати з конфігураціями в прод середовищі не варто, це буде розглянуто в наступних лабораторних
            value: demo
          volumeMounts: # прив'язка контейнеру, до *volume*
            - mountPath: /var/lib/postgresql/data
              name: postgredb 
      volumes: # визначення *volume*, прив'язка до PersistentVolumeClaim
        - name: postgredb
          persistentVolumeClaim:
            claimName: demo-storage
